<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
     <!-- To include it add the following line -->
    <!-- <xacro:include filename="example_gazebo.xacro" /> -->
    <gazebo reference="base_link">
        <material>Gazebo/Red</material>
    </gazebo>

    <xacro:macro name="color_wheels" params="name">
        <gazebo reference="wheel_${name}_link">
            <mu1>0.2</mu1>
            <mu2>0.2</mu2>
            <material>Gazebo/Yellow</material>
        </gazebo>
    </xacro:macro>

    <xacro:color_wheels name="front_left"/>
    <xacro:color_wheels name="front_right"/>
    <xacro:color_wheels name="rear_left"/>
    <xacro:color_wheels name="rear_right"/>

    <!-- Controller for the 4-wheeled robot -->
    <gazebo>
        <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">

            <!-- Control update rate in Hz -->
            <updateRate>100.0</updateRate>


            <!-- Leave this empty otherwise, there will be problems with sending control commands -->
            <robotNamespace></robotNamespace>

            <!-- Robot kinematics -->
            <leftFrontJoint>wheel_front_left_joint</leftFrontJoint>
            <rightFrontJoint>wheel_front_right_joint</rightFrontJoint>
            <leftRearJoint>wheel_rear_left_joint</leftRearJoint>
            <rightRearJoint>wheel_rear_right_joint</rightRearJoint>
            <wheelSeparation>${width+2*0.5}</wheelSeparation>
            <wheelDiameter>${2*0.15}</wheelDiameter>

            <!-- Maximum torque which the wheels can produce, in Nm, defaults to 5 Nm -->
            <torque>1</torque>


            <!-- Topic to receive geometry_msgs/Twist message commands, defaults to 'cmd_vel' -->
            <commandTopic>cmd_vel</commandTopic>
            <!-- Topic to publish nav_msgs/Odometry messages, defaults to 'odom' -->
            <odometryTopic>odom</odometryTopic>
            <!-- Odometry frame, defaulst to 'odom' -->
            <odometryFrame>odom</odometryFrame>
            <!-- Robot frame to calculate odometry from, defaults to 'base_footprint' -->
            <robotBaseFrame>base_footprint</robotBaseFrame>
            <!-- Set to true to publish transforms for the wheel links, defaults to false -->
            <publishWheelTF>true</publishWheelTF>
            <!-- Set to true to publish transforms for the odometry, defaults to true -->
            <publishOdom>true</publishOdom>
            <!-- Set to true to publish sensor_msgs/JointState on /joint_states for the wheel joints, defaults to false -->
            <publishWheelJointState>true</publishWheelJointState>

            <!-- This part is required by Gazebo -->
            <covariance_x>0.0001</covariance_x>
            <covariance_y>0.0001</covariance_y>
            <covariance_yaw>0.01</covariance_yaw>

        </plugin>
    </gazebo>
    <gazebo reference="camera_link">
        <material>Gazebo/Green</material>
        <sensor type="camera" name="camera">
        <update_rate>30.0</update_rate>
        <visualize></visualize>
        <camera name="head">
            <horizontal_fov>1.3962634</horizontal_fov>
            <image>
            <width>800</width>
            <height>800</height>
            <format>R8G8B8</format>
            </image>
            <clip>
            <near>0.02</near>
            <far>300</far>
            </clip>
        </camera>
        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>0.0</updateRate>
            <cameraName>spcbot/camera</cameraName>
            <imageTopicName>image_raw</imageTopicName>
            <cameraInfoTopicName>camera_info</cameraInfoTopicName>
            <frameName>camera</frameName>
            <hackBaseline>0.07</hackBaseline>
            <distortionK1>0.0</distortionK1>
            <distortionK2>0.0</distortionK2>
            <distortionK3>0.0</distortionK3>
            <distortionT1>0.0</distortionT1>
            <distortionT2>0.0</distortionT2>
        </plugin>
        </sensor>
    </gazebo>
    
</robot>





